services:
  - type: web
    name: image-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    workingDir: backend
    envVars:
      - key: FLASK_ENV
        value: production