services:
  - type: web
    name: ai-image-detector
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: python app.py
    workingDir: backend
    envVars:
      - key: FLASK_ENV
        value: production