services:
  - type: web
    name: your-service-name
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    pythonVersion: 3.11

